### ISSUE TITLE
Warning - Atomic add may lose precision

### ISSUE THREAD

**Issue by SantosRAC** [jgolob/phylogroups#2]
Hello @jgolob , I hope you are doing well.

I am currently trying the phylotypes package. I do not know if it has any significant impact on the calculations, but I see this warning (I guess it is a Taichi message) every time I run the script:

![image](https://github.com/jgolob/phylotypes/assets/7959954/fd8819ed-dccc-4549-a95a-f46867a3886a)

It does not raise any error and apparently finishes providing the output (ASV - phylotype associations file).

Cheers

**Comment by jgolob** [comment]
Cheers! Thank you for trying the tool!
This should not have a substantive effect on the output--and is likely related to details of your specific python environment. With that said, I will continue to curse the nature of floating point numbers in general.

**Comment by SantosRAC** [comment]
Great! Thanks a lot, @jgolob !
